# Generated by Django 5.1.1 on 2024-11-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopper',
        ),
    ]
