# Generated by Django 5.1.1 on 2024-11-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'product'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='staff',
            new_name='user',
        ),
    ]
