# Generated by Django 5.1.1 on 2024-11-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0004_rename_user_order_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
